# Use postgres/example user/password credentials
version: '3.8'

services:

  db:
    image: postgres:12.6
    restart: always
    environment:
      POSTGRES_PASSWORD: masterkey
    ports:
      - 5432:5432
    volumes:  
      - ./db:/var/lib/postgresql/data
      
